config/routes.rb
Rails.application.routes.draw do
  root 'stocks#index'
  resources :products
  resources :shelters
  resources :supplies
  resources :stocks
  resources :categories
  resources :transactions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/supply.rb
class Supply < ApplicationRecord
    has_many :products
    has_many :transactions, through: :products

    belongs_to :category

    def collect_products_with_transactions
        products = Product.where(supply_id: self.id).includes(:transactions)
        
        products.map do |product|
          { 
            product: product, 
            transactions: product.transactions.to_a
          }
        end
    end
    
    def calculate_total(transactions, product_quantity = 1)
        transactions.reduce(0) do |sum, t|
            case t.transaction_type
            when "IN"
                sum += t.quantity * product_quantity
            when "OUT"
                sum -= t.quantity * product_quantity
            end
            sum
        end
    end
    
    def total_stock
        pwt = collect_products_with_transactions
        transactions = pwt.flat_map { |e| e[:transactions] }
        calculate_total(transactions)
    end
    
    def total_quantity
        pwt = collect_products_with_transactions
        pwt.reduce(0) do |sum, entry|
          sum + calculate_total(entry[:transactions], entry[:product].quantity)
        end
    end

    # 以下はChatGPTにリファクタさせる前
    # TODO: なぜこれが同じ機構なのか考える

    # def calculate_total_stock(transactions)
    #     sum = 0

    #     transactions.each do |t|
    #         if t.transaction_type == "IN"
    #             sum += t.quantity
    #         elsif transaction.transaction_type == "OUT"
    #             sum -= t.quantity
    #         end
    #     end
    #     sum
    # end

    # def calculate_total_quantity(products_with_transactions)
    #     sum = 0

    #     products_with_transactions.each do |pwt|
    #         product_quantity = pwt[:product].quantity

    #         pwt[:transactions].each do |t|
    #             if t.transaction_type == "IN"
    #                 sum += t.quantity * product_quantity
    #             elsif t.transaction_type == "OUT"
    #                 sum -= t.quantity *  product_quantity
    #             end
    #         end
    #     end
    #     sum
    # end

    # def collect_products_with_transactions
    #     products = Product.where(supply_id: self.id).includes(:transactions)
        
    #     products_with_transactions = products.map do |product|
    #         { 
    #             product: product, 
    #             transactions: product.transactions.to_a,
    #         }
    #     end
        
    #     products_with_transactions
    # end

    # def total_stock
    #     pwt = self.collect_products_with_transactions
    #     transactions = pwt.flat_map { |e| e[:transactions] }
    #     total = calculate_total_stock(transactions)
    #     total
    # end
    
    # def total_quantity
    #     pwt = self.collect_products_with_transactions
    #     total = calculate_total_quantity(pwt)
    #     total
    # end
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  before_action :set_supply, only: %i[ show edit update destroy ]

  # GET /supplies or /supplies.json
  def index
    @supplies = Supply.includes(:category).all
  end

  # GET /supplies/1 or /supplies/1.json
  def show
  end

  # GET /supplies/new
  def new
    @supply = Supply.new
  end

  # GET /supplies/1/edit
  def edit
  end

  # POST /supplies or /supplies.json
  def create
    @supply = Supply.new(supply_params)

    respond_to do |format|
      if @supply.save
        format.html { redirect_to supply_url(@supply), notice: "supply was successfully created." }
        format.json { render :show, status: :created, location: @supply }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplies/1 or /supplies/1.json
  def update
    respond_to do |format|
      if @supply.update(supply_params)
        format.html { redirect_to supply_url(@supply), notice: "supply was successfully updated." }
        format.json { render :show, status: :ok, location: @supply }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplies/1 or /supplies/1.json
  def destroy
    @supply.destroy

    respond_to do |format|
      format.html { redirect_to supplies_url, notice: "supply was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supply
      @supply = Supply.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supply_params
      params.require(:supply).permit(:name, :description, :unit, :category_id)
    end
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/supplies/_form.html.erb
<%= form_with(model: supply) do |form| %>
  <% if supply.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(supply.errors.count, "error") %> prohibited this supply from being saved:</h2>

      <ul>
        <% supply.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :unit, style: "display: block" %>
    <%= form.text_field :unit %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, prompt: "Select a Category" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/supplies/_supply.html.erb
<div id="<%= dom_id supply %>">
  <p>
    <strong>Name:</strong>
    <%= supply.name %>
  </p>

  <p>
    <strong>Category Id:</strong>
    <%= supply.category_id %>
  </p>

  <p>
    <strong>Unit:</strong>
    <%= supply.unit %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= supply.description %>
  </p>

</div>

app/views/supplies/create.html.erb
<h1>Supplies#create</h1>
<p>Find me in app/views/supplies/create.html.erb</p>

app/views/supplies/destroy.html.erb
<h1>Supplies#destroy</h1>
<p>Find me in app/views/supplies/destroy.html.erb</p>

app/views/supplies/edit.html.erb
<h1>Editing supply</h1>

<%= render "form", supply: @supply %>

<br>

<div>
  <%= link_to "Show this supply", @supply %> |
  <%= link_to "Back to supplies", supplies_path %>
</div>

app/views/supplies/index.html.erb
<h1>Supplies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desctription</th>
      <th>Unit</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @supplies.each do |supply| %>
      <tr>
        <td><%= supply.name %></td>
        <td><%= supply.description %></td>
        <td><%= supply.unit %></td>
        <td><%= supply.category.name %></td>
        <td><%= link_to 'Show', supply %></td>
        <td><%= link_to 'Edit', edit_supply_path(supply) %></td>
        <td><%= link_to 'Destroy', supply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New supply', new_supply_path %>

app/views/supplies/new.html.erb
<h1>New supply</h1>

<%= render "form", supply: @supply %>

<br>

<div>
  <%= link_to "Back to supplies", supplies_path %>
</div>

app/views/supplies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @supply %>

<div>
  <%= link_to "Edit this supply", edit_supply_path(@supply) %> |
  <%= link_to "Back to supplies", supplies_path %>

  <%= button_to "Destroy this supply", @supply, method: :delete %>
</div>

app/views/supplies/update.html.erb
<h1>Supplies#update</h1>
<p>Find me in app/views/supplies/update.html.erb</p>