config/routes.rb
Rails.application.routes.draw do
  root 'stocks#index'
  resources :products
  resources :shelters
  resources :supplies
  resources :stocks
  resources :categories
  resources :transactions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: "transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:transaction_type, :transaction_date, :quantity, :product_id, :shelter_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :transaction_type, style: "display: block" %>
    <div>
      <%= form.radio_button :transaction_type, "IN" %>
      <%= form.label :transaction_type_IN, "IN" %>
    </div>
    <div>
      <%= form.radio_button :transaction_type, "OUT" %>
      <%= form.label :transaction_type_OUT, "OUT" %>
    </div>
  </div>

  <div>
    <%= form.label :transaction_date, style: "display: block" %>
    <%= form.date_field :transaction_date %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.collection_select :product_id, Product.all, :id, :name, prompt: "Select a Product" %>
  </div>

  <div>
    <%= form.label :shelter_id, style: "display: block" %>
    <%= form.collection_select :shelter_id, Shelter.all, :id, :name, prompt: "Select a Shelter" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Product Id:</strong>
    <%= transaction.product_id %>
  </p>

  <p>
    <strong>Shelter Id:</strong>
    <%= transaction.shelter_id %>
  </p>

  <p>
    <strong>Transaction Type:</strong>
    <%= transaction.transaction_type %>
  </p>

  <p>
    <strong>Transaction Date:</strong>
    <%= transaction.transaction_date %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= transaction.quantity %>
  </p>

</div>

app/views/transactions/create.html.erb
<h1>Transactions#create</h1>
<p>Find me in app/views/transactions/create.html.erb</p>

app/views/transactions/destroy.html.erb
<h1>Transactions#destroy</h1>
<p>Find me in app/views/transactions/destroy.html.erb</p>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Product Id</th>
      <th>Shelter Id</th>
      <th>Transaction Type</th>
      <th>Transaction Date</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.product_id %></td>
        <td><%= transaction.shelter_id %></td>
        <td><%= transaction.transaction_type %></td>
        <td><%= transaction.transaction_date %></td>
        <td><%= transaction.quantity %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>

app/views/transactions/update.html.erb
<h1>Transactions#update</h1>
<p>Find me in app/views/transactions/update.html.erb</p>